server:
    port: 8099
spring:
    application:
        name: client-provider-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
    instance:
        prefer-ip-address: true
feign:
    hystrix:
        enabled: true
management:
    endpoints:
        web:
            exposure:
                include: hystrix.stream