server:
    port: 9088
spring:
    application:
        name: client-turbine-dashboard


eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8888}/eureka/
    instance:
        prefer-ip-address: true
management:
    security:
        enabled: false
    endpoints:
        web:
            exposure:
                include: hystrix.stream
turbine:
    appConfig: client-hello-service,client-provider-service
    clusterNameExpression: "'default'"