server:
    port: 8062
eureka:
    instance:
        prefer-ip-address: true
        status-page-url-path: /actuator/info
        health-check-url-path: /actuator/health
        hostname: localhost
        metadataMap.zone: zone2
#    server:
#        waitTimeInMsWhenSyncEmpty: 0
#        enableSelfPreservation: false
#        remoteRegionUrlsWithName:
#            region-west: http://localhost:8063/eureka/
    client:
        register-with-eureka: true
        fetch-registry: true
        region: region-east
        availability-zones:
            region-east: zone1,zone2
        service-url:
            zone1: http://localhost:8061/eureka/
            zone2: http://localhost:8062/eureka/