server:
    port: 8063
eureka:
    instance:
        prefer-ip-address: true
        status-page-url-path: /actuator/info
        health-check-url-path: /actuator/health
        hostname: localhost
        metadataMap.zone: zone3
    server:
        waitTimeInMsWhenSyncEmpty: 0
        enableSelfPreservation: false
        remoteRegionUrlsWithName:
            region-west: http://localhost:8061/eureka/
    client:
        register-with-eureka: true
        fetch-registry: true
        region: region-west
        availability-zones:
            region-east: zone3,zone4
        service-url:
            zone1: http://localhost:8063/eureka/
            zone2: http://localhost:8064/eureka/
